syms f(x) p(x);
syms p0(x) p1(x) p2(x) p3(x);
p0(x)=1; p1(x)=x; p2(x)=x^2; p3(x)=x^3;
f(x)=exp(x)+1/(1+x^2);
p(x)=1;
%f(x)=1/(1+x^2)+1/x-sin(x);
disp("Функция f(x)="+string(f*p));
disp("Первообразная для функции f(x) F(x)="+string(int(f*p)));
a=input("Введите левый конец промежутка интегрирования: ");
b=input("Введите правый конец промежутка интегрирования: ");
m=input("Введите число участков m: ");
skf(f*p,a,b,m);
% skf(p0*p,a,b,m);
% skf(p1*p,a,b,m);
% skf(p2*p,a,b,m);
% skf(p3*p,a,b,m);

function skf(f,a,b,m)
h=(b-a)/m;
K=a:h:(b-h);
w=sum(double(subs(f,(a+h):h:(b-h))));
q=sum(double(subs(f,K+h/2)));
J=double(subs(int(f),b)-subs(int(f),a));
disp("Для функции " + string(f) +" выполняется численное интегрирование по составным квадратурным формулам");
disp("Значение интеграла: "+num2str(J));
fprintf('\n');
J1=h*(double(subs(f,a))+w);
disp("Значение по формуле левых прямоугольников: "+num2str(J1));
disp("Абсолютная погрешность для формулы левых прямоугольников: "+num2str(abs(J1-J)));
[x1,y1]=fminbnd(string(-abs(diff(f))),a,b);
y1=-y1;
R1=(b-a)^2/(2*m)*y1;
disp("Теоретическая погрешность для формулы левых прямоугольников: "+num2str(R1));
fprintf('\n');
J2=h*(double(subs(f,b))+w);
disp("Значение по формуле правых прямоугольников: "+num2str(J2));
disp("Абсолютная погрешность для формулы правых прямоугольников: "+num2str(abs(J2-J)));
disp("Теоретическая погрешность для формулы правых прямоугольников: "+num2str(R1));
fprintf('\n');
J3=h*q;
disp("Значение по формуле средних прямоугольников: "+num2str(J3));
disp("Абсолютная погрешность для формулы средних прямоугольников: "+num2str(abs(J3-J)));
[x2,y2]=fminbnd(string(-abs(diff(diff(f)))),a,b);
y2=-y2;
R2=(b-a)^3/(24*m^2)*y2;
disp("Теоретическая погрешность для формулы средних прямоугольников: "+num2str(R2));
fprintf('\n');
J4=h/2*(double(subs(f,b))+double(subs(f,a))+2*w);
disp("Значение по формуле трапеций: "+num2str(J4));
disp("Абсолютная погрешность для формулы трапеций: "+num2str(abs(J4-J)));
disp("Теоретическая погрешность для формулы трапеций: "+num2str(2*R2));
fprintf('\n');
J5=h/6*(double(subs(f,b))+double(subs(f,a))+2*w+4*q);
disp("Значение по формуле Симпсона: "+num2str(J5));
disp("Абсолютная погрешность для формулы Симпсона: "+num2str(abs(J5-J)));
[x3,y3]=fminbnd(string(-abs(diff(diff(diff(diff(f)))))),a,b);
y3=-y3;
R3=(b-a)^5/(2880*m^4)*y3;
disp("Теоретическая погрешность для формулы Симпсона: "+num2str(R3));
end