syms f(x) p(x);
syms p0(x) p1(x) p2(x) p3(x);
p0(x)=1; p1(x)=x; p2(x)=x^2; p3(x)=x^3;
f(x)=exp(x)+1/(1+x^2);
p(x)=1;
%f(x)=1/(1+x^2)+1/x-sin(x);
disp("Функция f(x)="+string(f*p));
disp("Первообразная для функции f(x) F(x)="+string(int(f*p)));
a=input("Введите левый конец промежутка интегрирования: ");
b=input("Введите правый конец промежутка интегрирования: ");
m=input("Введите число участков m: ");
l=input("Введите во сколько раз увеличить число делений: ");
skf(f*p,a,b,m,l);
% skf(p0*p,a,b,m,l);
% skf(p1*p,a,b,m,l);
% skf(p2*p,a,b,m,l);
% skf(p3*p,a,b,m,l);

function skf(f,a,b,m,l)
h=(b-a)/m;
h1=(b-a)/(m*l);
K=a:h:(b-h);
K1=a:h1:(b-h1);
w=sum(double(subs(f,(a+h):h:(b-h))));
w1=sum(double(subs(f,(a+h1):h1:(b-h1))));
q=sum(double(subs(f,K+h/2)));
q1=sum(double(subs(f,K1+h1/2)));
J=double(subs(int(f),b)-subs(int(f),a));

disp("Для функции " + string(f) +" выполняется численное интегрирование по составным квадратурным формулам");
disp("Значение интеграла: "+num2str(J));
fprintf('\n');
J1m=h*(double(subs(f,a))+w);
J1l=h1*(double(subs(f,a))+w1);
disp("Значение по формуле левых прямоугольников для разбиения m*l: "+num2str(J1l)+" Для m разбиений: "+num2str(J1m));
disp("Абсолютная погрешность для формулы левых прямоугольников для разбиения m*l: "+num2str(abs(J1l-J)));
r=1;
J1r=(l^r*J1l-J1m)/(l^r-1);
disp("Уточненное значение по методу Рунге: "+num2str(J1r));
disp("Абсолютная погрешность для уточненного значения: "+num2str(abs(J1r-J)));
fprintf('\n');
J2m=h*(double(subs(f,b))+w);
J2l=h1*(double(subs(f,b))+w1);
disp("Значение по формуле правых прямоугольников для разбиения m*l: "+num2str(J2l)+" Для m разбиений: "+num2str(J2m));
disp("Абсолютная погрешность для формулы правых прямоугольников для разбиения m*l: "+num2str(abs(J2l-J)));
r=1;
J2r=(l^r*J2l-J2m)/(l^r-1);
disp("Уточненное значение по методу Рунге: "+num2str(J2r));
disp("Абсолютная погрешность для уточненного значения: "+num2str(abs(J2r-J)));
fprintf('\n');
J3m=h*q;
J3l=h1*q1;
disp("Значение по формуле средних прямоугольников для разбиения m*l: "+num2str(J3l)+" Для m разбиений: "+num2str(J3m));
disp("Абсолютная погрешность для формулы средних прямоугольников для разбиения m*l: "+num2str(abs(J3l-J)));
r=2;
J3r=(l^r*J3l-J3m)/(l^r-1);
disp("Уточненное значение по методу Рунге: "+num2str(J3r));
disp("Абсолютная погрешность для уточненного значения: "+num2str(abs(J3r-J)));
fprintf('\n');
J4m=h/2*(double(subs(f,b))+double(subs(f,a))+2*w);
J4l=h1/2*(double(subs(f,b))+double(subs(f,a))+2*w1);
disp("Значение по формуле трапеций для разбиения m*l: "+num2str(J4l)+" Для m разбиений: "+num2str(J4m));
disp("Абсолютная погрешность для формулы трапеций для разбиения m*l: "+num2str(abs(J4l-J)));
r=2;
J4r=(l^r*J4l-J4m)/(l^r-1);
disp("Уточненное значение по методу Рунге: "+num2str(J4r));
disp("Абсолютная погрешность для уточненного значения: "+num2str(abs(J4r-J)));
fprintf('\n');
J5m=h/6*(double(subs(f,b))+double(subs(f,a))+2*w+4*q);
J5l=h1/6*(double(subs(f,b))+double(subs(f,a))+2*w1+4*q1);
disp("Значение по формуле Симпсона для разбиения m*l: "+num2str(J5l)+" Для m разбиений: "+num2str(J5m));
disp("Абсолютная погрешность для формулы Симпсона для разбиения m*l: "+num2str(abs(J5l-J)));
r=4;
J5r=(l^r*J5l-J5m)/(l^r-1);
disp("Уточненное значение по методу Рунге: "+num2str(J5r));
disp("Абсолютная погрешность для уточненного значения: "+num2str(abs(J5r-J)));
end